const EcosystemConfig = [
  {
    logo: '/assets/images/ozeety.png',
    name: 'Ozeety',
    desc: 'Ozeety_desc',
    color: '#00FBCE',
    title: 'Ozeety_title',
    url: 'ozeety.com',
  },
  {
    logo: '/assets/images/oztcard.png',
    name: 'OZT card',
    title: 'OZTCard_title',
    desc: 'OZTCard_desc',
    color: '#0066FF',
    url: 'oztcard.com',
  },
  {
    logo: '/assets/images/flashx.png',
    name: 'FlashX',
    title: 'FlashX_title',
    desc: 'FlashX_desc',
    color: '#FF4E4E',
    url: 'flashxchanger.com',
  },
  {
    logo: '/assets/images/flashwallet.png',
    name: 'FlashWallet',
    title: 'FlashWallet_title',
    desc: 'FlashWallet_desc',
    color: '#FC4FF6',
  },
  {
    logo: '/assets/images/flashcryptostation.png',
    name: 'FlashCryptostation',
    title: 'Flashcryptostation_title',
    desc: 'Flashcryptostation_desc',
    color: '#00FF85',
  },
  {
    logo: '/assets/images/flashgo.png',
    name: 'FlashGo',
    title: 'FlashGo_title',
    desc: 'FlashGo_desc',
    color: '#FFCC40',
  },
  {
    logo: '/assets/images/flashdata.png',
    name: 'FlashData',
    title: 'FlashData_title',
    desc: 'FlashData_desc',
    color: '#002CCA',
  },
  {
    logo: '/assets/images/flashadchain.png',
    name: 'FlashAdchain',
    title: 'FlashAdchain_title',
    desc: 'FlashAdchain_desc',
    color: '#A400FF',
  },
  {
    logo: '/assets/images/flashcare.png',
    name: 'FlashCare',
    title: 'FlashCare_title',
    desc: 'FlashCare_desc',
    color: '#009AFF',
  },
];

export default EcosystemConfig;
